-- 云鹤系统数据库补充结构
-- 在 Supabase 的 SQL Editor 里复制整份运行。
-- 它不会删除你已有的数据。

create table if not exists diary_entries (
  id text primary key,
  title text not null,
  entry_date date default current_date,
  mood text default '平静',
  tags text default '',
  body text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table diary_entries enable row level security;

create table if not exists media_items (
  id bigint generated by default as identity primary key,
  title text not null,
  description text default '',
  kind text not null check (kind in ('photo', 'video')),
  url text not null,
  path text not null,
  status text default 'published',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table media_items enable row level security;

alter table media_items
add column if not exists shot_at date;

create table if not exists content_backups (
  id bigint generated by default as identity primary key,
  content_id bigint,
  operation text not null default 'delete',
  snapshot jsonb not null,
  created_by text,
  created_at timestamptz default now()
);

alter table content_backups enable row level security;

create table if not exists wechat_articles (
  id bigint generated by default as identity primary key,
  wechat_article_key text unique not null,
  account_id text default 'gh_29c8bc4a87bf',
  media_id text,
  title text not null,
  digest text default '',
  author text default '',
  content_url text default '',
  source_url text default '',
  thumb_media_id text default '',
  category text default '未分类',
  topic text default '未分类',
  ai_summary text default '',
  status text default 'imported',
  raw jsonb default '{}'::jsonb,
  published_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table wechat_articles enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'media_items'
      and policyname = 'public media select'
  ) then
    create policy "public media select"
    on media_items
    for select
    using (status = 'published');
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'wechat_articles'
      and policyname = 'public wechat published select'
  ) then
    create policy "public wechat published select"
    on wechat_articles
    for select
    using (status = 'published');
  end if;
end $$;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'media',
  'media',
  true,
  5368709120,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'image/heic',
    'image/heif',
    'application/octet-stream',
    'video/mp4',
    'video/quicktime',
    'video/webm'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'public media files select'
  ) then
    create policy "public media files select"
    on storage.objects
    for select
    using (bucket_id = 'media');
  end if;
end $$;
