-- 访客登记表
-- 在 Supabase SQL Editor 里运行一次。
-- 只新增 visitor_logs，不会删除已有内容。

create table if not exists visitor_logs (
  id bigint generated by default as identity primary key,
  display_name text,
  source text not null,
  purpose text not null,
  message text,
  page_url text,
  user_agent text,
  is_important boolean not null default false,
  highlight_color text not null default 'none',
  admin_note text,
  updated_at timestamptz,
  created_at timestamptz default now()
);

alter table visitor_logs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'visitor_logs'
      and policyname = 'public visitor log insert'
  ) then
    create policy "public visitor log insert"
    on visitor_logs
    for insert
    with check (
      source in ('公众号', '视频', '朋友推荐', '搜索', '其他')
      and purpose in ('看文章', '看案例', '看作品', '了解云鹤系统', '其他')
    );
  end if;
end $$;
