-- 云鹤系统：访客登记完整建表与后台管理升级
-- 可独立、重复执行；不会删除或覆盖已有访客数据。

create table if not exists public.visitor_logs (
  id bigint generated by default as identity primary key,
  display_name text,
  source text not null,
  purpose text not null,
  message text,
  page_url text,
  user_agent text,
  is_important boolean not null default false,
  highlight_color text not null default 'none',
  admin_note text,
  updated_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.visitor_logs
  add column if not exists is_important boolean not null default false,
  add column if not exists highlight_color text not null default 'none',
  add column if not exists admin_note text,
  add column if not exists updated_at timestamptz;

alter table public.visitor_logs
  drop constraint if exists visitor_logs_highlight_color_check;

alter table public.visitor_logs
  add constraint visitor_logs_highlight_color_check
  check (highlight_color in ('none', 'red', 'amber', 'green', 'blue'));

create index if not exists visitor_logs_important_created_idx
  on public.visitor_logs (is_important desc, created_at desc);

alter table public.visitor_logs enable row level security;

revoke all on table public.visitor_logs from anon, authenticated;
grant insert on table public.visitor_logs to anon, authenticated;
grant all on table public.visitor_logs to service_role;

grant usage, select on sequence public.visitor_logs_id_seq to anon, authenticated;
grant all on sequence public.visitor_logs_id_seq to service_role;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'visitor_logs'
      and policyname = 'public visitor log insert'
  ) then
    create policy "public visitor log insert"
    on public.visitor_logs
    for insert
    to anon, authenticated
    with check (
      source in ('公众号', '视频', '朋友推荐', '搜索', '其他')
      and purpose in ('看文章', '看案例', '看作品', '了解云鹤系统', '其他')
      and is_important = false
      and highlight_color = 'none'
      and admin_note is null
    );
  end if;
end $$;

select
  column_name,
  data_type,
  is_nullable,
  column_default
from information_schema.columns
where table_schema = 'public'
  and table_name = 'visitor_logs'
order by ordinal_position;
